using System;
using UnityEngine;

public class OrientationMath : MonoBehaviour
{
  public static Orientation Rotate(Orientation orientation, OrientationRotation rot)
  {
    switch ($"{orientation}{rot}")
    {
      case "ldl":
        return Orientation.lf;
      case "ldr":
        return Orientation.lb;
      case "ldd":
        return Orientation.bd;
      case "ldu":
        return Orientation.fd;
      case "ldb":
        return Orientation.ul;
      case "ldf":
        return Orientation.dr;
      case "lul":
        return Orientation.lb;
      case "lur":
        return Orientation.lf;
      case "lud":
        return Orientation.bu;
      case "luu":
        return Orientation.fu;
      case "lub":
        return Orientation.ur;
      case "luf":
        return Orientation.dl;
      case "lbl":
        return Orientation.ld;
      case "lbr":
        return Orientation.lu;
      case "lbd":
        return Orientation.br;
      case "lbu":
        return Orientation.fl;
      case "lbb":
        return Orientation.ub;
      case "lbf":
        return Orientation.db;
      case "lfl":
        return Orientation.lu;
      case "lfr":
        return Orientation.ld;
      case "lfd":
        return Orientation.bl;
      case "lfu":
        return Orientation.fr;
      case "lfb":
        return Orientation.uf;
      case "lff":
        return Orientation.df;
      case "rdl":
        return Orientation.rf;
      case "rdr":
        return Orientation.rb;
      case "rdd":
        return Orientation.fd;
      case "rdu":
        return Orientation.bd;
      case "rdb":
        return Orientation.dl;
      case "rdf":
        return Orientation.ur;
      case "rul":
        return Orientation.rb;
      case "rur":
        return Orientation.rf;
      case "rud":
        return Orientation.fu;
      case "ruu":
        return Orientation.bu;
      case "rub":
        return Orientation.dr;
      case "ruf":
        return Orientation.ul;
      case "rbl":
        return Orientation.rd;
      case "rbr":
        return Orientation.ru;
      case "rbd":
        return Orientation.fr;
      case "rbu":
        return Orientation.bl;
      case "rbb":
        return Orientation.db;
      case "rbf":
        return Orientation.ub;
      case "rfl":
        return Orientation.ru;
      case "rfr":
        return Orientation.rd;
      case "rfd":
        return Orientation.fl;
      case "rfu":
        return Orientation.br;
      case "rfb":
        return Orientation.df;
      case "rff":
        return Orientation.uf;
      case "dll":
        return Orientation.fl;
      case "dlr":
        return Orientation.bl;
      case "dld":
        return Orientation.db;
      case "dlu":
        return Orientation.df;
      case "dlb":
        return Orientation.lu;
      case "dlf":
        return Orientation.rd;
      case "drl":
        return Orientation.fr;
      case "drr":
        return Orientation.br;
      case "drd":
        return Orientation.df;
      case "dru":
        return Orientation.db;
      case "drb":
        return Orientation.ld;
      case "drf":
        return Orientation.ru;
      case "dbl":
        return Orientation.fd;
      case "dbr":
        return Orientation.bu;
      case "dbd":
        return Orientation.dr;
      case "dbu":
        return Orientation.dl;
      case "dbb":
        return Orientation.lb;
      case "dbf":
        return Orientation.rb;
      case "dfl":
        return Orientation.fu;
      case "dfr":
        return Orientation.bd;
      case "dfd":
        return Orientation.dl;
      case "dfu":
        return Orientation.dr;
      case "dfb":
        return Orientation.lf;
      case "dff":
        return Orientation.rf;
      case "ull":
        return Orientation.bl;
      case "ulr":
        return Orientation.fl;
      case "uld":
        return Orientation.ub;
      case "ulu":
        return Orientation.uf;
      case "ulb":
        return Orientation.ru;
      case "ulf":
        return Orientation.ld;
      case "url":
        return Orientation.br;
      case "urr":
        return Orientation.fr;
      case "urd":
        return Orientation.uf;
      case "uru":
        return Orientation.ub;
      case "urb":
        return Orientation.rd;
      case "urf":
        return Orientation.lu;
      case "ubl":
        return Orientation.bd;
      case "ubr":
        return Orientation.fu;
      case "ubd":
        return Orientation.ur;
      case "ubu":
        return Orientation.ul;
      case "ubb":
        return Orientation.rb;
      case "ubf":
        return Orientation.lb;
      case "ufl":
        return Orientation.bu;
      case "ufr":
        return Orientation.fd;
      case "ufd":
        return Orientation.ul;
      case "ufu":
        return Orientation.ur;
      case "ufb":
        return Orientation.rf;
      case "uff":
        return Orientation.lf;
      case "bll":
        return Orientation.dl;
      case "blr":
        return Orientation.ul;
      case "bld":
        return Orientation.rb;
      case "blu":
        return Orientation.lf;
      case "blb":
        return Orientation.bu;
      case "blf":
        return Orientation.bd;
      case "brl":
        return Orientation.dr;
      case "brr":
        return Orientation.ur;
      case "brd":
        return Orientation.rf;
      case "bru":
        return Orientation.lb;
      case "brb":
        return Orientation.bd;
      case "brf":
        return Orientation.bu;
      case "bdl":
        return Orientation.df;
      case "bdr":
        return Orientation.ub;
      case "bdd":
        return Orientation.rd;
      case "bdu":
        return Orientation.ld;
      case "bdb":
        return Orientation.bl;
      case "bdf":
        return Orientation.br;
      case "bul":
        return Orientation.db;
      case "bur":
        return Orientation.uf;
      case "bud":
        return Orientation.ru;
      case "buu":
        return Orientation.lu;
      case "bub":
        return Orientation.br;
      case "buf":
        return Orientation.bl;
      case "fll":
        return Orientation.ul;
      case "flr":
        return Orientation.dl;
      case "fld":
        return Orientation.lb;
      case "flu":
        return Orientation.rf;
      case "flb":
        return Orientation.fu;
      case "flf":
        return Orientation.fd;
      case "frl":
        return Orientation.ur;
      case "frr":
        return Orientation.dr;
      case "frd":
        return Orientation.lf;
      case "fru":
        return Orientation.rb;
      case "frb":
        return Orientation.fd;
      case "frf":
        return Orientation.fu;
      case "fdl":
        return Orientation.uf;
      case "fdr":
        return Orientation.db;
      case "fdd":
        return Orientation.ld;
      case "fdu":
        return Orientation.rd;
      case "fdb":
        return Orientation.fl;
      case "fdf":
        return Orientation.fr;
      case "ful":
        return Orientation.ub;
      case "fur":
        return Orientation.df;
      case "fud":
        return Orientation.lu;
      case "fuu":
        return Orientation.ru;
      case "fub":
        return Orientation.fr;
      case "fuf":
        return Orientation.fl;
    }
    throw new NotImplementedException("Unknown Rotation");
  }
}
